"""
Contract generation via standard Gemini API (non-live).

When the live agent signals it's ready to generate a contract, this module
uses the full conversation transcript to generate a comprehensive legal
contract via a standard (non-streaming) Gemini API call.
"""
import logging
import os
from google import genai

logger = logging.getLogger(__name__)

# Use a text-capable model for contract generation
CONTRACT_MODEL = os.getenv("GEMINI_CONTRACT_MODEL", "gemini-2.5-flash")

CONTRACT_GENERATION_PROMPT = """\
You are an expert legal contract drafter. Based on the conversation below
between a user and a legal assistant, generate a COMPREHENSIVE, PROFESSIONAL
legal contract.

Extract all relevant details from the conversation (names, terms, amounts,
dates, conditions, etc.) and produce a complete contract.

The contract MUST include ALL of these sections:

1. TITLE (e.g., "LEASE AGREEMENT" or "SALES AGREEMENT")
2. PREAMBLE — full date, full legal names, roles (Seller/Buyer, Landlord/Tenant, etc.)
3. RECITALS — brief background ("WHEREAS the Seller wishes to sell...")
4. DEFINITIONS — define key terms used in the agreement
5. SUBJECT MATTER — detailed description of what is being contracted
6. CONSIDERATION / PRICE — exact amount, currency, payment schedule
7. OBLIGATIONS OF EACH PARTY — specific duties, timelines
8. REPRESENTATIONS AND WARRANTIES — what each party guarantees
9. DELIVERY / PERFORMANCE — when, where, and how
10. TERM AND TERMINATION — duration, how to terminate, notice periods
11. CONFIDENTIALITY (if applicable)
12. LIMITATION OF LIABILITY
13. INDEMNIFICATION
14. DISPUTE RESOLUTION — governing law, mediation, arbitration, jurisdiction
15. GENERAL PROVISIONS — entire agreement, amendments, severability, waiver, notices
16. SIGNATURES BLOCK — names, signature lines, date lines, witness lines

FORMATTING RULES:
- Use plain text ONLY. No markdown (no **, ##, or * bullets).
- Use numbered sections (1., 2., 3.) and lettered subsections (a., b., c.).
- Use ALL CAPS for section headings.
- Fill in ALL dates, names, and jurisdictions from the conversation.
  NEVER use [brackets] or placeholders.
- If no date was specified, use "the date of execution of this Agreement."
- If no specific state was given, use the country's general laws.
- The contract must be at least 800 words. Be thorough and professional.
- End with: "DISCLAIMER: This document is a template generated by AI and
  should be reviewed by a qualified legal professional before execution."

CONVERSATION TRANSCRIPT:
{conversation}

Generate the complete contract text now. Output ONLY the contract text,
nothing else — no preamble, no explanation before or after.
"""


async def generate_contract_text(conversation: str) -> str | None:
    """Generate a full contract using a standard Gemini API call.
    
    Args:
        conversation: The full conversation transcript between user and agent.
    
    Returns:
        The full contract text, or None if generation failed.
    """
    try:
        client = genai.Client()
        
        prompt = CONTRACT_GENERATION_PROMPT.format(conversation=conversation)
        
        logger.info(f"Generating contract with {CONTRACT_MODEL}...")
        logger.info(f"Conversation context: {conversation[:500]}...")
        
        response = await client.aio.models.generate_content(
            model=CONTRACT_MODEL,
            contents=prompt,
        )
        
        contract_text = response.text
        
        if contract_text and len(contract_text) > 100:
            # Clean any markdown that might have slipped through
            contract_text = (
                contract_text
                .replace("**", "")
                .replace("##", "")
                .replace("# ", "")
                .strip()
            )
            logger.info(f"✅ Contract generated ({len(contract_text)} chars)")
            return contract_text
        else:
            logger.warning(f"Contract too short: {len(contract_text) if contract_text else 0} chars")
            return None
            
    except Exception as e:
        logger.error(f"❌ Contract generation failed: {e}", exc_info=True)
        return None
