"""
Contract generation tool functions for the ADK agent.

These are the decoupled business-logic functions from the old CrewAI pipeline,
re-packaged as plain Python functions that the Google ADK agent can call via
Gemini's tool-calling (function-calling) capability.
"""
import json
from typing import Optional


# ---------------------------------------------------------------------------
# Contract categories & types (preserved from schemas/contract.py)
# ---------------------------------------------------------------------------
CONTRACT_CATEGORIES = {
    "Business Contracts": [
        "Sales Agreement", "Service Agreement", "Non-Disclosure Agreement (NDA)",
        "Partnership Agreement", "Joint Venture Agreement", "Franchise Agreement",
        "Distribution Agreement", "Supply Agreement", "License Agreement",
        "Employment Contract", "Consulting Agreement", "Non-Compete Agreement",
        "Independent Contractor Agreement", "Sales Representative Agreement",
        "Manufacturing Agreement",
    ],
    "Real Estate Contracts": [
        "Lease Agreement", "Purchase Agreement", "Mortgage Agreement",
        "Tenancy Agreement", "Property Management Agreement",
        "Real Estate Listing Agreement", "Commercial Lease Agreement",
        "Rental Application",
    ],
    "Financial Contracts": [
        "Loan Agreement", "Investment Agreement", "Promissory Note",
        "Guaranty Agreement", "Credit Agreement",
    ],
    "Employment Contracts": [
        "Employment Offer Letter", "Employee Handbook", "Severance Agreement",
        "Employment Termination Agreement",
    ],
    "Intellectual Property Contracts": [
        "Copyright Assignment", "Patent License Agreement",
        "Trademark License Agreement", "Confidentiality Agreement",
    ],
    "Personal Contracts": [
        "Prenuptial Agreement", "Postnuptial Agreement", "Separation Agreement",
        "Settlement Agreement", "Child Custody Agreement",
        "Power of Attorney", "Living Will",
    ],
    "Technology Contracts": [
        "Software License Agreement", "IT Services Agreement",
        "Website Development Agreement",
    ],
    "Miscellaneous Contracts": [
        "Event Planning Agreement", "Maintenance Agreement",
        "Vendor Agreement", "Freelance Contract",
    ],
}

SUPPORTED_COUNTRIES = [
    "United States",
    "United Kingdom",
    "Singapore",
    "Australia",
    "Canada",
]


# ---------------------------------------------------------------------------
# ADK tool functions — plain Python, must return dict
# ---------------------------------------------------------------------------

def get_contract_categories() -> dict:
    """Return all available contract categories and their types.

    Use this tool when the user asks what types of contracts are available,
    or when you need to help them choose a contract type.

    Returns:
        dict: A dictionary with status and a mapping of categories to types.
    """
    return {
        "status": "success",
        "categories": CONTRACT_CATEGORIES,
    }


def get_supported_countries() -> dict:
    """Return the list of supported jurisdictions / countries.

    Use this tool when the user asks which countries or jurisdictions are
    supported for contract generation.

    Returns:
        dict: A dictionary with status and the list of supported countries.
    """
    return {
        "status": "success",
        "countries": SUPPORTED_COUNTRIES,
    }


def generate_contract(
    contract_type: str,
    country: str,
    party_a_name: str,
    party_b_name: str,
    key_terms: str,
    additional_details: str = "",
) -> dict:
    """Generate a complete legal contract document based on the provided parameters.

    IMPORTANT: Call this tool ONLY after you have gathered ALL the required
    information from the user through the voice conversation. You must have at
    minimum: the contract type, the country/jurisdiction, both party names, and
    the key terms.

    The tool returns a structured JSON payload that the frontend will use to
    render the contract. The actual contract text is generated by YOU (the
    Gemini model) — this tool simply packages and delivers it.

    Args:
        contract_type: The specific type of contract, e.g. "Non-Disclosure Agreement (NDA)".
        country: The country or jurisdiction for legal compliance.
        party_a_name: Full legal name of the first party.
        party_b_name: Full legal name of the second party.
        key_terms: A summary of the key terms, obligations, and conditions
                   discussed during the conversation.
        additional_details: Any extra context or special clauses the user
                            requested.

    Returns:
        dict: A dictionary containing the contract metadata. The actual
              contract text should be generated by the model and spoken/sent
              to the user separately.
    """
    # Validate contract_type
    valid_types = []
    for types in CONTRACT_CATEGORIES.values():
        valid_types.extend(types)

    if contract_type not in valid_types:
        return {
            "status": "error",
            "error_message": (
                f"Unknown contract type '{contract_type}'. "
                f"Use the get_contract_categories tool to see valid types."
            ),
        }

    # Validate country
    if country not in SUPPORTED_COUNTRIES:
        return {
            "status": "error",
            "error_message": (
                f"Country '{country}' is not currently supported. "
                f"Supported countries: {', '.join(SUPPORTED_COUNTRIES)}."
            ),
        }

    # Build the contract metadata payload
    contract_data = {
        "status": "success",
        "contract": {
            "contract_type": contract_type,
            "country": country,
            "party_a": party_a_name,
            "party_b": party_b_name,
            "key_terms": key_terms,
            "additional_details": additional_details,
        },
        "instruction_to_model": (
            "Now draft the FULL legal contract text for the user. Include all "
            "standard sections: title, preamble, definitions, obligations, "
            "terms & conditions, dispute resolution, signatures block, and "
            "any jurisdiction-specific clauses required by the laws of "
            f"{country}. Make it complete and ready to use."
        ),
    }

    return contract_data
